version: '3'
services:
  mongo:
    image: mongo:3.3
    container_name: mongo
    hostname: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
  widestage:
    build: .
    image: widestage/widestage-pro
    container_name: WST-PRO
    hostname: widestage
    links:
      - mongo
    environment:
      - IP=0.0.0.0
      - MONGOHOST=mongo
    ports:
      - "80:80"
volumes:
  db-data:
