version: '3'
services:
  mongo:
    image: mongo:3.3
    container_name: mongo
    hostname: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "37017:27017"
  widestage:
    build: .
    image: widestage/widestage
    container_name: WST
    hostname: widestage
    links:
      - mongo
    environment:
      - IP=0.0.0.0
      - MONGOHOST=mongo
    volumes:
      - ./docker-entrypoint.sh:/srv/app/docker-entrypoint.sh
    ports:
      - "8089:8089"
      - "9229:9229"
      - "9230:9230"
volumes:
  db-data:
